version: '3.7'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - app_db
    volumes:
      - /app/.venv/
      - /app/__pycache__/
      - /app/src/__pycache__/
    
  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16.3
    env_file:
      - .env
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  app_db_data:
    driver: "local"
